(* ********************************************************************************************* *)
(* ********************************* Type Definitions ****************************************** *)
(* ********************************************************************************************* *)

type typ = TYPE_none          (* Not to be used *)
         | TYPE_unit          (* Unit *)
         | TYPE_bool          (* Bool *)
         | TYPE_char          (* Char *)
         | TYPE_int           (* Int *)
         | TYPE_float         (* Float *)
         | TYPE_array of      (* Array *)
            typ *    (* Array Type *)
            int      (* Number of Dimensions *)
         | TYPE_ref of        (* Reference (mutable) *)
            typ      (* Reference to which type *)
         | TYPE_func of       (* Function *)
            typ *    (* Parameter type *)
            typ      (* Result type *)
         | TYPE_userdef of    (* User Defined Type *)
            string   (* Name of the User Defined Type *)
         | TYPE_duck of       (* Special Type - Used for Type Inference *)
            int      (* Counter *)

(* ********************************************************************************************* *)
(* ************************************ Functions ********************************************** *)
(* ********************************************************************************************* *)
 
val sizeOfType     : typ -> int                       (* Calculate the size of a type        *)
val equalType      : typ -> typ -> bool               (* Checks if two types are equal       *)
val funcReturnType : typ -> typ                       (* Finds the return type of a function *)
val pprint_typ     : Format.formatter -> typ -> unit  (* Pretty Print a Type                 *)
